<a href="https://colab.research.google.com/github/Ananya-Upadhyaya/Ananya-Upadhyaya/blob/main/Python_Numpy(22_09_22).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
#Age of 6 people

ages_list = [10, 5, 8, 32, 65, 43]
ages_list.sort()
print(ages_list)

[5, 8, 10, 32, 43, 65]


In [8]:
# 3 main ways to instantiate a Numpy ndarray object

ages = np.array(ages_list)
print(type(ages))
print(ages)

<class 'numpy.ndarray'>
[ 5  8 10 32 43 65]


In [14]:
print(ages)
print("Size:\t" , ages.size)
print("Shape:\t", ages.shape)

[ 5  8 10 32 43 65]
Size:	 6
Shape:	 (6,)


In [16]:
zeroArr = np.zeros(7)
print(zeroArr)

[0. 0. 0. 0. 0. 0. 0.]


In [17]:
# new list containing the weights of these 6 people.

weight_list = [32, 18, 26, 60, 55, 65]
print(weight_list)

[32, 18, 26, 60, 55, 65]


In [18]:
people = np.array([ages_list, weight_list])

print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[ 5  8 10 32 43 65]
 [32 18 26 60 55 65]]
Size:	 12
Shape:	 (2, 6)


In [26]:
# 2 X 6 = 1 X 12 = 4 X 3 = 3 X 4 = 12 X 1 

people = people.reshape(2,6)
print("People:\t" , people)
print("Size:\t" , people.size)
print("Shape:\t", people.shape)

People:	 [[ 5  8 10 32 43 65]
 [32 18 26 60 55 65]]
Size:	 12
Shape:	 (2, 6)


In [27]:
# EXCERCISE

# Generate a 1D numpy array with the values [7, 9, 65, 33, 85, 99]

import numpy as np

arr = np.array([7, 9, 65, 33, 85, 99])
print(arr)

[ 7  9 65 33 85 99]


In [32]:
# Generate a matrix (2D numpy array) of the values:

arr1 = np.array([[1, 2, 4],[2, 3, 0],[0, 5, 1]])
print(arr1)

[[1 2 4]
 [2 3 0]
 [0 5 1]]


In [37]:
x = np.array([[1, 2, 4],[2, 3, 0],[0, 5, 1]])
print("changing shape to 2,4")
print(x.shape)

changing shape to 2,4
(3, 3)


In [50]:
print('Initialised array')
c = np.array([1, 2, 4, 2, 3, 0, 0, 5, 1])
print(c)

print('current shape of the array')
print(c.shape)
      
# modifying array according to new dimensions
print('changing shape to 3, 3')
c.shape = (3, 3)
print(c)

Initialised array
[1 2 4 2 3 0 0 5 1]
current shape of the array
(9,)
changing shape to 3, 3
[[1 2 4]
 [2 3 0]
 [0 5 1]]


In [84]:
# Array Generation

# np.arange()
times_table = np.arange(1, 55, 5)
print(times_table)



[ 1  6 11 16 21 26 31 36 41 46 51]


In [60]:
# np.linspace()

#five_spaced = np.linspace(0,50,11)
#print(five_spaced)

five_spaced = np.linspace(0,50,5)
print(five_spaced)

[ 0.  12.5 25.  37.5 50. ]


In [65]:
# .repeat()

Arr = np.repeat(4, 6)
print(Arr)


[4 4 4 4 4 4]


In [75]:
# np.eye()

identity_matrix = np.eye(2,4)
print(identity_matrix)




[[1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [76]:
identity_matrix = np.eye(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


**Operations**

In [89]:
times_table

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [90]:
print("1:", 2 * times_table)
print("2:", 10 + times_table)
print("3:", times_table - 1)
print("4:", times_table/5)
print("5:", times_table **2)
print("6:", times_table < 20)

1: [  0  10  20  30  40  50  60  70  80  90 100]
2: [10 15 20 25 30 35 40 45 50 55 60]
3: [-1  4  9 14 19 24 29 34 39 44 49]
4: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
5: [   0   25  100  225  400  625  900 1225 1600 2025 2500]
6: [ True  True  True  True False False False False False False False]


 **SpeedTest**

In [96]:
List = list(range(0,201,5))
List

[0,
 5,
 10,
 15,
 20,
 25,
 30,
 35,
 40,
 45,
 50,
 55,
 60,
 65,
 70,
 75,
 80,
 85,
 90,
 95,
 100,
 105,
 110,
 115,
 120,
 125,
 130,
 135,
 140,
 145,
 150,
 155,
 160,
 165,
 170,
 175,
 180,
 185,
 190,
 195,
 200]

In [98]:
five_times_table_lge = np.arange(0,5001,5)
five_times_table_lge

array([   0,    5,   10, ..., 4990, 4995, 5000])

In [99]:
%timeit five_times_table_lge + 5

1.34 µs ± 16 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [100]:
%timeit [e + 5 for e in fives_list]


59.4 µs ± 763 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [102]:
words = np.array(["ten", "nine", "eight", "seven", "six"])

print(np.isin(words, 'e'))

["e" in word for word in words]

[False False False False False]


[True, True, True, True, False]

**Transpose**

In [105]:
people.shape = (2, 6)
print(people, "\n")
print(people.T)

[[ 5  8 10 32 43 65]
 [32 18 26 60 55 65]] 

[[ 5 32]
 [ 8 18]
 [10 26]
 [32 60]
 [43 55]
 [65 65]]


 **DataTypes**

In [106]:
people.dtype

dtype('int64')

In [107]:
# What is the data type of the below ndarray?

ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
ages_with_strings

array(['10', '5', '8', '32', '65', '43'], dtype='<U21')

In [119]:
# What is the dtype of this array?

ages_with_strings = np.array([10, 5, 8, '32', '65', '43'], dtype='int32')
ages_with_strings

array([10,  5,  8, 32, 65, 43], dtype=int32)

In [120]:
ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)

['10' '5' '8' '32' '65' '43']


In [122]:
ages_with_strings.dtype = 'int32'
print(ages_with_strings)

[49 48  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 56  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0 51 50  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0  0  0  0 54 53  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0  0  0  0 52 51  0  0  0  0  0  0  0  0  0  0  0  0  0
  0  0  0  0  0  0]


In [111]:
ages_with_strings.size

126

In [112]:
ages_with_strings.size/21

6.0

In [113]:
np.array([10, 5, 8, '32', '65', '43']).size

6

In [114]:
#  .astype()

ages_with_strings = np.array([10, 5, 8, '32', '65', '43'])
print(ages_with_strings)
print(ages_with_strings.astype('int32'))

['10' '5' '8' '32' '65' '43']
[10  5  8 32 65 43]


**Exercise**

In [115]:
# Create an array of string numbers, but use dtype to make it an array of floats.

ages_with_strings = np.array(['10', '5', '8', '32', '65', '43'])
print(ages_with_strings.astype('float'))


[10.  5.  8. 32. 65. 43.]


In [124]:
#  Transpose the matrix, printing the new size and shape.

A = np.array([[1, 2], [3, 4]])
A_T = A.transpose()
print(A_T)

[[1 3]
 [2 4]]


In [129]:
# Use the .astype() method to convert the array to boolean.

A = np.array([[1, 0], [0, 4]])
A.astype(bool)

array([[ True, False],
       [False,  True]])

**Array Slicing Operations**

In [132]:
five_times_table

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52])

In [133]:
five_times_table[0]

1

In [134]:
five_times_table[-1]

52

In [135]:
five_times_table[:4]

array([ 1,  4,  7, 10])

In [137]:
five_times_table[4:]

array([13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49, 52])

In [152]:
# We can also slice an n-dim ndarray., specifying the slice operation accross each axis.

print(people)
people[:2, :5]

[[ 5  8 10 32 43 65]
 [32 18 26 60 55 65]]


array([[ 5,  8, 10, 32, 43],
       [32, 18, 26, 60, 55]])

**Exercise**

In [151]:
# Create a numpy array with 50 zeros

array = np.zeros(50)
print(array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0.]


In [153]:
# Create a np array of 2 repeated 20 times

Arr = np.repeat(2,20)
print(Arr)


[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [157]:
# For one of the arrays generated: 
# Get the first five values

arr = np.array([[10, 5, 8], [32, 65, 43],[0, 5, 1],[1, 13, 56],[2, 4, 6],[9, 0, 4],[3, 8, 5]])
print("Original array: ")
print(arr)
arr1= arr[:5, :]
print("First 5 rows of the above array:")
print(arr1)


Original array: 
[[10  5  8]
 [32 65 43]
 [ 0  5  1]
 [ 1 13 56]
 [ 2  4  6]
 [ 9  0  4]
 [ 3  8  5]]
First 5 rows of the above array:
[[10  5  8]
 [32 65 43]
 [ 0  5  1]
 [ 1 13 56]
 [ 2  4  6]]


In [173]:
# Get the last 3 values

arr = np.array([[10, 5, 8], [32, 65, 43],[0, 5, 1],[1, 13, 56],[2, 4, 6],[9, 0, 4],[3, 8, 5]])
print("Original array: ")
print(arr)
arr1= arr[-3:]
print("last 3 values from array:")
print(arr1)



Original array: 
[[10  5  8]
 [32 65 43]
 [ 0  5  1]
 [ 1 13 56]
 [ 2  4  6]
 [ 9  0  4]
 [ 3  8  5]]
last 3 values from array:
[[2 4 6]
 [9 0 4]
 [3 8 5]]


In [172]:
# Get the 4th value to the 7th value

arr = np.array([[10, 5, 8], [32, 65, 43],[0, 5, 1],[1, 13, 56],[2, 4, 6],[9, 0, 4],[3, 8, 5],[0, 24, 65]])
print("Original array: ")
print(arr)
arr1= arr[4],arr[7]
print("value of 4th and 7th of array:")
print(arr1)

Original array: 
[[10  5  8]
 [32 65 43]
 [ 0  5  1]
 [ 1 13 56]
 [ 2  4  6]
 [ 9  0  4]
 [ 3  8  5]
 [ 0 24 65]]
value of 4th and 7th of array:
(array([2, 4, 6]), array([ 0, 24, 65]))


In [174]:
# .flip() 

reverse_five_times_table = np.flip(five_times_table)
reverse_five_times_table

array([52, 49, 46, 43, 40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10,  7,  4,
        1])

In [177]:
reverse_five_times_table = five_times_table[-1::-1]
print(reverse_five_times_table)
five_times_table

[52 49 46 43 40 37 34 31 28 25 22 19 16 13 10  7  4  1]


array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52])

In [178]:
#Every 3rd element starting from 0

five_times_table[0::3]

array([ 1, 10, 19, 28, 37, 46])

**Exercise**

In [181]:
# Take one of the arrays you defined and Reverse it

reverse_arr2 = np.array([10, 5, 8, 32, 65, 48, 12, 78, 89, 100 ])
reverse_arr2 = np.flip(reverse_arr2)
print(reverse_arr2)


[100  89  78  12  48  65  32   8   5  10]


In [187]:
# Only keep every 4th element.

arr2 = [10, 5, 8, 32, 65, 48, 12, 78, 89, 100 ]

every_4th = arr2[::4]

print(every_4th)



[10, 65, 89]


In [191]:
# Get every 2nd element, starting from the last and moving backwards.

print(arr2[-1::-2])

[100, 78, 48, 32, 5]


**Stats**

In [188]:
np.array([1.65432, 5.98765]).round(2)

array([1.65, 5.99])

In [190]:
nums = np.arange(0, 4, 0.2555)
print(nums)

[0.     0.2555 0.511  0.7665 1.022  1.2775 1.533  1.7885 2.044  2.2995
 2.555  2.8105 3.066  3.3215 3.577  3.8325]


**Exercise**

In [192]:
# Compute min, max, sum, mean, median, variance, and standard deviation of the above array, all to to 2 decimal places.

print("min = ", np.min(nums).round(2))
print("max = ", np.max(nums).round(2))
print("sum = ", np.sum(nums).round(2))
print("mean = ", np.mean(nums).round(2))
print("median = ", np.median(nums).round(2))
print("var = ", np.var(nums).round(2))
print("std = ", np.std(nums).round(2))

min =  0.0
max =  3.83
sum =  30.66
mean =  1.92
median =  1.92
var =  1.39
std =  1.18


**Random**

In [193]:
flip = np.random.choice([0,1], 10)
flip

array([0, 0, 1, 0, 1, 1, 1, 1, 0, 1])

In [202]:
np.random.rand(10,20,9)

array([[[0.99416425, 0.45717738, 0.32570487, ..., 0.77953842,
         0.89394246, 0.50238304],
        [0.45658638, 0.95531464, 0.52642635, ..., 0.73610996,
         0.86528941, 0.97013098],
        [0.29786925, 0.53602749, 0.87503791, ..., 0.62975586,
         0.96398632, 0.11712981],
        ...,
        [0.96742215, 0.39289965, 0.25488368, ..., 0.12690786,
         0.21953363, 0.30056252],
        [0.61588072, 0.12843666, 0.38120356, ..., 0.53051242,
         0.23011888, 0.40167389],
        [0.06236419, 0.03040121, 0.03461957, ..., 0.14782518,
         0.40080776, 0.49416135]],

       [[0.23102457, 0.81566785, 0.94595454, ..., 0.3510616 ,
         0.91311873, 0.13053001],
        [0.87388124, 0.08398026, 0.96454968, ..., 0.82273952,
         0.23059034, 0.99809469],
        [0.46167781, 0.63080812, 0.79804878, ..., 0.22852705,
         0.05283716, 0.43596113],
        ...,
        [0.21027299, 0.05398656, 0.95399504, ..., 0.61363148,
         0.75056035, 0.14505997],
        [0.6

In [196]:
# np.random.normal()

mu, sigma = 0, 0.1 
s = np.random.normal(mu, sigma, 1000)
print(s)

[-1.34819228e-01 -1.23307293e-01 -4.68998539e-02 -5.06555129e-02
 -6.76682616e-02  2.42718132e-02 -8.29925867e-02 -1.30372784e-01
 -1.39948626e-01  6.46525594e-02 -3.47285268e-03 -5.64376571e-02
 -6.74511201e-03  6.59529039e-02  6.27624207e-02  3.47141298e-02
  5.58942960e-02 -4.06477247e-02 -4.91689106e-02 -3.09240396e-02
  8.02891163e-02 -1.38419614e-02 -1.02479899e-02  7.06814325e-02
 -1.68783372e-01 -7.93103268e-02  2.08571402e-01  7.33433050e-02
 -1.36278919e-01  8.16960545e-02  1.01414532e-01  1.15411192e-01
 -1.36070526e-01 -2.05331277e-01  9.11002817e-02 -3.72639506e-02
 -6.86387627e-02  3.01813429e-02 -1.51246673e-01  5.03304887e-02
 -6.74472432e-02  8.01134351e-02  8.77363814e-02  9.27576789e-02
 -1.68688566e-01  2.24156376e-02  2.55574455e-02  6.89763331e-02
 -1.02025199e-01 -6.51515098e-02 -1.17091514e-01  2.97237938e-02
  3.20751332e-02 -6.39159507e-02 -2.26382621e-02  6.29110028e-03
 -1.30890864e-01  1.42163808e-01 -1.04281606e-01  1.38500622e-01
  7.55519839e-02 -7.07993

**EXCERCISE**

In [199]:
#2.Simulate a two-sided coin toss that is NOT fair: it is twice as likely to have head than tails.
coin = np.random.choice(['Head','Head','Tails'], 2)
print(coin)

array(['Head', 'Head'], dtype='<U5')

In [205]:
#Exercise:1.Simulate a six-sided dice using numpy.random.choice(), generate a list of values you would obtain from 10 throws.
dice = np.random.choice([1,6], 10)
dice

array([1, 1, 6, 6, 1, 6, 6, 1, 1, 6])